### ISSUE TITLE
Check if safe_name should be used:

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.autoinclude#17]
Reading https://github.com/plone/plone.autoinclude/pull/16 it came to my mind a [PR I did years ago on mr.developer](https://github.com/fschulze/mr.developer/pull/150/files) to deal with a similar issue. 

So probably instead of doing:
```
ep.dist.project_name.replace("-", "_")
```
it might be better and more comprehensive to use:
```
from setuptools.package_index import safe_name
```

I did not really have time to investigate further, I just opened this issue to share my fading memories.

**Comment by mauritsvanrees** [comment]
We did this, and it is included in version 1.0.0. See PR #21. But then we realised it was wrong, see further remarks in that PR, so we reverted it. That will be in a near-future version 1.0.1.
