### ISSUE TITLE
Error: Couldn't find a distribution for 'plone.autoinclude==1.0.0a3'.

### ISSUE THREAD

**Issue by wesleybl** [plone/plone.autoinclude#18]
I have the following buildout:

```cfg
[buildout]

extends =
    base.cfg
    https://dist.plone.org/release/6.0-dev/versions.cfg


find-links +=
    https://dist.plone.org/release/6.0-dev/
    https://dist.plone.org/thirdparty/

...
```

So when running the buildout I get the following error:

```bash
Installing instance.
Getting distribution for 'plone.autoinclude==1.0.0a3'.
While:
  Installing instance.
  Getting distribution for 'plone.autoinclude==1.0.0a3'.
Error: Couldn't find a distribution for 'plone.autoinclude==1.0.0a3'.
```

I don't have `plone.autoinclude` in my download cache. What am I missing?

**Comment by wesleybl** [comment]
Well the problem doesn't seem to be with the `plone.autoinclude`. I put it in the download cache, and I had a problem with `plone.app.dexterity`:

```bash
Getting distribution for 'plone.app.dexterity==3.0.0a7'.
While:
  Installing instance.
  Getting distribution for 'plone.app.dexterity==3.0.0a7'.
Error: Couldn't find a distribution for 'plone.app.dexterity==3.0.0a7'.
```

Any tips?

**Comment by mauritsvanrees** [comment]
Just a small side note: there is nothing in Plone 6 that needs https://dist.plone.org/thirdparty/ in the `find-links`. Not in Plone 5 and 4 either I think.

O, we still have it in `buildout.plonetest` itself I see... Should be safe to remove in 5.2 and 6.0. Perhaps just 6.0 to be on the safe side.

**Comment by mauritsvanrees** [comment]
PR for thirdparty: https://github.com/collective/buildout.plonetest/pull/90
